import Image from "next/image";
import { Container } from "../Container";

/**
 * "Built by" — institutional provenance strip on a cream interlude.
 *
 * Logos use the *-clear.png variants generated by scripts/process-logos.cjs:
 * the original black backgrounds knocked out to true alpha=0, original
 * brand colours preserved. So EY-Parthenon's yellow flash, Amazon's
 * orange smile, and Berkeley's blue+seal all read at full saturation
 * against the cream paper.
 */

const LOGOS = [
  {
    name: "EY-Parthenon",
    src: "/logos/ey-parthenon-clear.png",
    width: 720,
    height: 200,
    h: "h-12 md:h-16",
  },
  {
    name: "UC Berkeley",
    src: "/logos/berkeley-clear.png",
    width: 1024,
    height: 576,
    h: "h-14 md:h-20",
  },
  {
    name: "Amazon",
    src: "/logos/amazon-clear.png",
    width: 1024,
    height: 330,
    h: "h-10 md:h-14",
  },
];

export function BuiltBy() {
  return (
    <section className="border-y border-rule-dark bg-cream py-14 md:py-20">
      <Container>
        <div className="grid grid-cols-1 items-center gap-10 md:grid-cols-12 md:gap-10">
          <p className="font-mono uppercase tracking-chrome2 text-[12px] text-muted md:col-span-4">
            Built by engineers and transactional professionals from
          </p>
          <div className="flex flex-wrap items-center gap-x-14 gap-y-8 md:col-span-8 md:justify-end md:gap-x-20">
            {LOGOS.map((logo) => (
              <Image
                key={logo.name}
                src={logo.src}
                alt={logo.name}
                width={logo.width}
                height={logo.height}
                priority
                className={`${logo.h} w-auto`}
              />
            ))}
          </div>
        </div>
      </Container>
    </section>
  );
}
